import type { HabitTemplate } from "@/types";

export const HABIT_TEMPLATES: HabitTemplate[] = [
  {
    name: "喝一杯水",
    description: "起床后第一件事，唤醒身体",
    icon: "💧",
    color: "#0ea5e9",
    category: "health",
    frequency: { type: "daily" },
    cue: "起床后，脚一落地",
    reward: "感受身体被唤醒的清爽",
    twoMinuteVersion: "喝一口水也算完成",
  },
  {
    name: "阅读 10 分钟",
    description: "积少成多，一年读完十本书",
    icon: "📚",
    color: "#8b5cf6",
    category: "learning",
    frequency: { type: "daily" },
    cue: "晚饭后泡一杯茶",
    reward: "享受沉浸的安静",
    twoMinuteVersion: "翻开书，读一页就好",
  },
  {
    name: "冥想 5 分钟",
    description: "观察呼吸，与自己相处",
    icon: "🧘",
    color: "#10b981",
    category: "mindfulness",
    frequency: { type: "daily" },
    cue: "刷完牙坐到瑜伽垫上",
    reward: "平静、清晰",
    twoMinuteVersion: "闭眼深呼吸 3 次",
  },
  {
    name: "运动 30 分钟",
    description: "走路、跑步、撸铁都算",
    icon: "🏃",
    color: "#f59e0b",
    category: "health",
    frequency: { type: "custom", daysOfWeek: [1, 3, 5] },
    cue: "下班换上运动鞋",
    reward: "汗水后的痛快感",
    twoMinuteVersion: "穿好运动鞋走出家门",
  },
  {
    name: "写日记",
    description: "记录今天三件值得感恩的事",
    icon: "✍️",
    color: "#ec4899",
    category: "mindfulness",
    frequency: { type: "daily" },
    cue: "睡前关灯前",
    reward: "梳理一天的成就感",
    twoMinuteVersion: "写一句话也行",
  },
  {
    name: "学英语",
    description: "背单词 / Duolingo / 听播客",
    icon: "🗣️",
    color: "#06b6d4",
    category: "learning",
    frequency: { type: "daily" },
    cue: "通勤路上打开 App",
    reward: "看到等级提升",
    twoMinuteVersion: "背 5 个单词",
  },
  {
    name: "早睡（23 点前）",
    description: "好睡眠是一切的基础",
    icon: "🌙",
    color: "#6366f1",
    category: "health",
    frequency: { type: "daily" },
    cue: "22:30 闹钟响起",
    reward: "第二天的精神饱满",
    twoMinuteVersion: "22:30 放下手机",
  },
  {
    name: "拉伸 5 分钟",
    description: "缓解久坐疲劳",
    icon: "🤸",
    color: "#84cc16",
    category: "health",
    frequency: { type: "daily" },
    cue: "起床/睡前在床边",
    reward: "身体打开的舒展感",
    twoMinuteVersion: "做一组颈部转动",
  },
  {
    name: "写代码 / 做项目",
    description: "副业、开源、个人成长",
    icon: "💻",
    color: "#0891b2",
    category: "work",
    frequency: { type: "daily" },
    cue: "晚 9 点关掉社交 App",
    reward: "看到提交记录增加",
    twoMinuteVersion: "打开编辑器写一行",
  },
  {
    name: "晒太阳 15 分钟",
    description: "调节生物钟，补充维生素 D",
    icon: "☀️",
    color: "#eab308",
    category: "health",
    frequency: { type: "daily" },
    cue: "上午十点的茶歇",
    reward: "心情变好",
    twoMinuteVersion: "到窗边站 2 分钟",
  },
  {
    name: "整理桌面 5 分钟",
    description: "环境整洁，思路清晰",
    icon: "🧹",
    color: "#a78bfa",
    category: "lifestyle",
    frequency: { type: "daily" },
    cue: "下班关电脑前",
    reward: "明天打开干净桌面的愉悦",
    twoMinuteVersion: "把杯子洗了",
  },
  {
    name: "联系一个朋友",
    description: "维系关系，胜过事后弥补",
    icon: "💬",
    color: "#f43f5e",
    category: "social",
    frequency: { type: "weekly", timesPerWeek: 3 },
    cue: "午饭后",
    reward: "被回应的温暖",
    twoMinuteVersion: "发一句'最近怎样'",
  },
  {
    name: "画画 / 写作",
    description: "创造的快乐",
    icon: "🎨",
    color: "#d946ef",
    category: "creativity",
    frequency: { type: "custom", daysOfWeek: [2, 4, 6] },
    cue: "周二四六晚 8 点",
    reward: "完成一个作品的成就",
    twoMinuteVersion: "在本子上随便画两笔",
  },
  {
    name: "戒糖（无奶茶/甜点）",
    description: "记录每个忍住的瞬间",
    icon: "🚫🍰",
    color: "#ef4444",
    category: "health",
    frequency: { type: "daily" },
    cue: "想喝奶茶时",
    reward: "皮肤变好、体重下降",
    twoMinuteVersion: "用气泡水代替",
  },
  {
    name: "做饭 / 自己带饭",
    description: "省钱又健康",
    icon: "🍳",
    color: "#f97316",
    category: "lifestyle",
    frequency: { type: "custom", daysOfWeek: [1, 2, 3, 4, 5] },
    cue: "前一晚睡前 10 分钟",
    reward: "省下的钱 + 满足感",
    twoMinuteVersion: "煮个鸡蛋",
  },
  {
    name: "写感恩三件事",
    description: "积极心理学经典实践",
    icon: "🙏",
    color: "#f59e0b",
    category: "mindfulness",
    frequency: { type: "daily" },
    cue: "睡前刷牙后",
    reward: "睡前心情平和",
    twoMinuteVersion: "只想一件事也行",
  },
  {
    name: "复盘今天",
    description: "我做对了什么 / 可以更好的是什么",
    icon: "🔍",
    color: "#3b82f6",
    category: "work",
    frequency: { type: "daily" },
    cue: "下班路上",
    reward: "持续成长的踏实",
    twoMinuteVersion: "想三个关键词",
  },
  {
    name: "练琴 / 乐器",
    description: "每天 15 分钟胜过周末 2 小时",
    icon: "🎸",
    color: "#dc2626",
    category: "creativity",
    frequency: { type: "daily" },
    cue: "下班一进门",
    reward: "技艺一点点进步",
    twoMinuteVersion: "拿起琴弹一段",
  },
  {
    name: "深度工作 90 分钟",
    description: "无干扰的高浓度工作",
    icon: "🎯",
    color: "#7c3aed",
    category: "work",
    frequency: { type: "custom", daysOfWeek: [1, 2, 3, 4, 5] },
    cue: "上午 9:30 关掉通知",
    reward: "完成核心任务的爽感",
    twoMinuteVersion: "番茄钟开始第一个 25 分钟",
  },
  {
    name: "记账",
    description: "知道钱花在哪",
    icon: "💰",
    color: "#16a34a",
    category: "lifestyle",
    frequency: { type: "daily" },
    cue: "睡前打开记账 App",
    reward: "对生活的掌控感",
    twoMinuteVersion: "记一笔最大的支出",
  },
  {
    name: "陪家人聊天",
    description: "10 分钟也好",
    icon: "👨‍👩‍👧",
    color: "#fb7185",
    category: "social",
    frequency: { type: "daily" },
    cue: "晚饭时间放下手机",
    reward: "亲密的连接",
    twoMinuteVersion: "发一条问候消息",
  },
  {
    name: "看一篇深度文章",
    description: "对抗碎片化",
    icon: "📰",
    color: "#0d9488",
    category: "learning",
    frequency: { type: "daily" },
    cue: "通勤路上",
    reward: "思考变深",
    twoMinuteVersion: "读完一段也行",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  health: "健康",
  learning: "学习",
  mindfulness: "心智",
  work: "工作",
  social: "社交",
  creativity: "创造",
  lifestyle: "生活",
  other: "其他",
};
